Fix building error
ERROR: "drm_global_mutex" [drivers/gpu/drm/i915/i915.ko] undefined!
ERROR: "access_process_vm" [drivers/gpu/drm/i915/i915.ko] undefined!

I did not find the root cause and surprised about android-ia branch

Signed-off-by: Jianxing Wang <wangjianxing5210@163.com>